// microservices/shared/constants/roles.js
export const ROLES = {
  SUPER_ADMIN: "SUPER_ADMIN",
  SITE_ADMIN: "SITE_ADMIN",
  OPERATOR: "OPERATOR",
  CLIENT_ADMIN: "CLIENT_ADMIN",
  CLIENT_USER: "CLIENT_USER"
};

export const PERMISSIONS = {
  SUPER_ADMIN: ["SITE_ADMIN", "OPERATOR", "CLIENT_ADMIN"],
  SITE_ADMIN: ["OPERATOR", "CLIENT_ADMIN"],
  OPERATOR: ["CLIENT_ADMIN"],
  CLIENT_ADMIN: ["CLIENT_USER"]
};
